#!/usr/bin/env bash

brew install pyenv || true
brew install pyenv-virtualenv || true
brew install pyenv-virtualenvwrapper || true

# https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
# set -euox pipefail
set -e

# https://gist.github.com/jonsuh/3c89c004888dfc7352be
# ----------------------------------
# Colors
# ----------------------------------
export NOCOLOR='\033[0m'
export RED='\033[0;31m'
export GREEN='\033[0;32m'
export ORANGE='\033[0;33m'
export BLUE='\033[0;34m'
export MAD_BLUE='\e[34m'
export PURPLE='\033[0;35m'
export CYAN='\033[0;36m'
export LIGHTGRAY='\033[0;37m'
export DARKGRAY='\033[1;30m'
export LIGHTRED='\033[1;31m'
export LIGHTGREEN='\033[1;32m'
export YELLOW='\033[1;33m'
export LIGHTBLUE='\033[1;34m'
export LIGHTPURPLE='\033[1;35m'
export LIGHTCYAN='\033[1;36m'
export WHITE='\033[1;37m'

if [[ x"$1" = x"" ]]; then
    echo -e " ${RED}[python-compile]${NOCOLOR} missing python major version, eg '3'"
    exit 1
fi

if [[ x"$2" = x"" ]]; then
    echo -e " ${RED}[python-compile]${NOCOLOR} missing python minor version, eg '6'"
    exit 1
fi

if [[ x"$3" = x"" ]]; then
    echo -e " ${RED}[python-compile]${NOCOLOR} missing python patch version, eg '12'"
    exit 1
fi

echo "Python major version?"

read _PY_VER_MAJOR

echo "Python minor version?"

read _PY_VER_MINOR

echo "Python patch version?"

read _PY_VER_MICRO

export _PY_VER_MAJOR
export _PY_VER_MINOR
export _PY_VER_MICRO

print_compile_flags
verify_keg_folders_exists


compile_python
