#!/usr/bin/env bash

# SOURCE: https://medium.com/@ssnehil/cutting-an-image-as-instagram-blocks-using-a-script-1b156d4240c3

if ! [ -x "$(command -v convert)" ]; then
  echo 'Error: ImageMagick is not installed.' >&2
  exit 1
fi

IMGPATH=""
if [ $# -eq  0 ]; then
  IMGPATH=$(osascript -e '
  tell application (path to frontmost application as text)
  set myFile to choose file with prompt "Please select an image to process:" of type {"public.image"}
  POSIX path of myFile
  end')
else
  IMGPATH=$1
fi

DV=3

WIDTH=`identify -ping -format '%w' "$IMGPATH"`
DIV=`echo $(($WIDTH/$DV))`
NEWSIZE=`echo $(($DIV*$DV))`

IMGDIR=`dirname "$IMGPATH"`
IMGNAME=`basename "$IMGPATH"`
NEWIMGPATH="$IMGDIR/temp_$IMGNAME"

FOLDERNAME=$IMGDIR/"insta-"`echo ${IMGNAME%.*}`
convert -resize "$NEWSIZE"x "$IMGPATH" "$NEWIMGPATH"

mkdir -p "$FOLDERNAME"
convert -crop "$DIV"x"$DIV" "$NEWIMGPATH" "$FOLDERNAME/%d.jpg"
rm "$NEWIMGPATH"
echo "DONE. Folder created at:"
echo "$FOLDERNAME"
open "$FOLDERNAME"

exit 1
