#!/usr/bin/env bash

# move all files into their respective folders based on size etc



# https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
# set -euox pipefail
set -e

# https://gist.github.com/jonsuh/3c89c004888dfc7352be
# ----------------------------------
# Colors
# ----------------------------------
export NOCOLOR='\033[0m'
export RED='\033[0;31m'
export GREEN='\033[0;32m'
export ORANGE='\033[0;33m'
export BLUE='\033[0;34m'
export MAD_BLUE='\e[34m'
export PURPLE='\033[0;35m'
export CYAN='\033[0;36m'
export LIGHTGRAY='\033[0;37m'
export DARKGRAY='\033[1;30m'
export LIGHTRED='\033[1;31m'
export LIGHTGREEN='\033[1;32m'
export YELLOW='\033[1;33m'
export LIGHTBLUE='\033[1;34m'
export LIGHTPURPLE='\033[1;35m'
export LIGHTCYAN='\033[1;36m'
export WHITE='\033[1;37m'

mkdir -p meme_sizes/{tiktok,instagram} || true
mkdir -p meme_sizes/instagram/{portrait,landscape,square} || true

echo -e " ${GREEN}[ffmpeg-mv]${NOCOLOR} ${CYAN}running${NOCOLOR} ffmpeg-mv\n"
rm -fv mv.txt
touch mv.txt
for filename in ./*ig-portrait*; do echo mv -fv "$filename" meme_sizes/instagram/portrait; done >> mv.txt
for filename in ./*ig-landscape*; do echo mv -fv "$filename" meme_sizes/instagram/landscape; done >> mv.txt
for filename in ./*ig-square*; do echo mv -fv "$filename" meme_sizes/instagram/square; done >> mv.txt
for filename in ./*tiktok*; do echo mv -fv "$filename" meme_sizes/tiktok; done >> mv.txt
cat mv.txt
echo -e " ${GREEN}[ffmpeg-mv]${NOCOLOR} ${CYAN}running${NOCOLOR} move commands\n"
bash mv.txt
rm mv.txt

