#!/usr/bin/env bash

# https://stackoverflow.com/questions/30130614/imagemagick-resize-image-rectangle-to-square-keep-aspect-ratio-of-main-objec
# set -euox pipefail
set -e

# https://gist.github.com/jonsuh/3c89c004888dfc7352be
# ----------------------------------
# Colors
# ----------------------------------
export NOCOLOR='\033[0m'
export RED='\033[0;31m'
export GREEN='\033[0;32m'
export ORANGE='\033[0;33m'
export BLUE='\033[0;34m'
export PURPLE='\033[0;35m'
export CYAN='\033[0;36m'
export LIGHTGRAY='\033[0;37m'
export DARKGRAY='\033[1;30m'
export LIGHTRED='\033[1;31m'
export LIGHTGREEN='\033[1;32m'
export YELLOW='\033[1;33m'
export LIGHTBLUE='\033[1;34m'
export LIGHTPURPLE='\033[1;35m'
export LIGHTCYAN='\033[1;36m'
export WHITE='\033[1;37m'

export LANDSCAPE=""
export SQUARE=""
export PORTRAIT=""


# default size
size_val="200x200"

while getopts ":hf:s:" opt; do
  case ${opt} in
    h ) # process option h
      ;;
    f ) # process option f
      filename_val=$OPTARG
      ;;
    s ) # process option size
      size_val="$OPTARG"
      ;;
    \? )
      echo "Invalid option: $OPTARG" 1>&2
      ;;
    : )
      echo "Invalid option: $OPTARG requires an argument" 1>&2
      ;;
  esac
done


# resize image to width 25, keeping aspect ratio
convert -geometry 25x src/image1.png out/image1.png

# resize image to height 25, keeping aspect ratio
convert -geometry x25 src/image1.png out/image1.png

# concatenate images horizontally
convert +append src/image1.png src/image2.png out/image12horiz.png

# concatenate images vertically
convert -append src/image1.png src/image2.png out/image12vert.png


export input_file="${filename_val}"
export full_path_input_file="$(pwd)/${filename_val}"
export get_extension=$(basename -- $input_file | cut -d"." -f2)
export full_path_output_file="square-$(uuidgen).${get_extension}"

tmpfile=$(mktemp /tmp/abc-script.XXXXXX)
echo -e " ${BLUE}[imagemagick-ig-resize]${NOCOLOR} tmpfile=${tmpfile}"

cat << EOF > "${tmpfile}"
aspectcrop -a 2:1 ${full_path_input_file} ${full_path_output_file}


EOF

echo -e " ${BLUE}[imagemagick-ig-resize]${NOCOLOR} cat ${tmpfile}"
cat "${tmpfile}"

bash  "${tmpfile}"

rm "$tmpfile"
